### ISSUE TITLE
Can the Prover verify the Witness?

### ISSUE THREAD

**Issue by zappso** [johnoliverdriscoll/ecc-acc#7]
Given the public key of the Accumulator, can a Prover verify a Witness?

**Comment by johnoliverdriscoll** [comment]
Great question. Based on the original construction described in the whitepaper, ${\bf Witness}(e_i) = g^{(e_0+c)(e_1+c)...(e_{i-2}+c)(e_{i-1}+c) \mod q}$, where $c$ is the private key, it was not possible to verify publicly because the verify function ${\bf Verify}(e_i, v_i) = z == v_i^{e_i+c \mod q}$ required knowledge of $c$.

However, I was able to reason that providing the additional information $w_i \leftarrow v_i^c$ allows a third party to use a new function ${\bf VerifyPublic}(e_i, v_i, w_i) = z == v_i^{e_i}w_i$ without knowledge of $c$. This of course requires knowledge of $z$, but that is not a sensitive value. Additionally, the ${\bf Prove}$ function must be updated to compute $w_i \leftarrow Q_{i+1}^1 Q_i^{e_0+e_1+...+e_{i-2}+e_{i-1}} ... Q_1^{e_0 e_1 + ... + e_{i-2} e_{i-1}} Q_0^{e_0 e_1 ... e_{i-2} e_{i-1}}$.

It wasn't immediately obvious to me, but all very trivial in hindsight. The new witness format $(v, w)$ is now adopted in the latest release.

https://github.com/johnoliverdriscoll/ecc-acc/releases/tag/v2.0.0
