### ISSUE TITLE
Constant time witness updates?

### ISSUE THREAD

**Issue by sangaman** [johnoliverdriscoll/ecc-acc#8]
First of all, thanks for sharing this awesome repo/demo.

I was curious about what it would take to modify the code to perform witness updates in constant time. In the README I see that such a feature is listed but crossed out. I see in the code that the prover needs to track and iterate through all the updates that have ever happened to produce updated witnesses - so not constant. The linked paper does claim to perform witness updates with "only one multiplication per addition or revocation". I haven't dug into how it's performed in the paper yet, and before I gave that a shot I thought I'd ask if you had any thoughts or plans re: making constant time witness updates with this repo.

Is this something the Accumulator class would do? Or is there a way an untrusted prover could create updated witnesses in constant time?

Thanks!

**Comment by johnoliverdriscoll** [comment]
The "constant" part of constant time updates actually refers to the time complexity *per witness being updated* so it is a bit of misnomer in the field of accumulator witnesses. All accumulators (that I'm aware of) require that every member's witness be updated when the accumulation is modified. If you're considering the time complexity of updating *every* witness, the best time complexity any system could hope to achieve is linear. So that's a given, let's just ignore it and focus on the time complexity *per witness*. The system is able to compute *a witness* in constant time, but only if the secret $c$ is known. As you suspect, this is only possible for the Accumulator class. I plan on supporting this at some point as well.

However, the Prover class must resort to brute force computation of the polynomial $G^{(e_1+c)(e_2+c)...(e_{n-1}+c)(e_n+c)}$ knowing only $e$ and the associated $Q_n = \prod^n{G^c}$. This is a quadratic operation as it requires calculation for $n \choose i$ for all $i = 0..n$.

It's been years since I did any research on cryptographic accumulators, but if you're looking for constant time witness calculation by an untrusted party, look into the [RSA implementation](https://github.com/johnoliverdriscoll/rsa-acc). Additionally, the ECC implementation in the [accumulator-rs](https://github.com/mikelodder7/accumulator-rs) repo may be based on a more flexible system, although I believe it has some different limitations, specifically set size. Hope this helps.

**Comment by johnoliverdriscoll** [comment]
Accumulator.prove is available as of version 3.1.0
